import numpy as np
import pandas as pd
import pyperclip
from jinja2 import Environment


def _ab(points0, odds0, pdo):
    b = pdo / np.log(2)
    a = points0 + b * np.log(odds0)
    return a, b


def prob2score(y_proba, points0=600, odds0=1 / 19, pdo=50):
    """Convert a model-predicted default probability to a standard credit score.

    Uses the standard scorecard formula to map predicted probabilities to interpretable scores.

    Parameters
    ----------
    y_proba: {float, array-like}
        Model predicted probability of default (bad outcome).
    points0: int, optional
        Base score. Defaults to 600.
    odds0: float, optional
        Bad/Good odds ratio at base score. Defaults to 1/19.
    pdo: int, optional
        Points to double the odds. Defaults to 50.

    Returns
    -------
    score: {float, array-like}
        Rounded standard credit score(s).
    """
    a, b = _ab(points0, odds0, pdo)
    return np.round(a - b * np.log(y_proba / (1 - y_proba)))


def scorecard(bins, intercept, coef, feature_names, points0=600, odds0=1 / 19, pdo=50):
    """Generate full credit scorecard from binning results and model coefficients.

    Combines feature binning data, model coefficients, and intercept term to
    calculate point values for each feature bin, plus a baseline score.

    Parameters
    ----------
    bins: dict[str, DataFrame]
        Binning results dictionary, key=feature name, value=bin DataFrame.
    intercept: float
        Intercept term from trained logistic regression model.
    coef: array-like of float
        Coefficients of independent variables from model.
    feature_names: array-like of str
        Names of features matching the order of `coef`.
    points0: int, optional
        Base score. Defaults to 600.
    odds0: float, optional
        Bad/Good odds ratio at base score. Defaults to 1/19.
    pdo: int, optional
        Points to double the odds. Defaults to 50.

    Returns
    -------
    scorecard_df: DataFrame
        Complete scorecard with columns 'variable', 'bin', and 'score'.
    """
    a, b = _ab(points0, odds0, pdo)
    dt = pd.concat(bins, axis=0, ignore_index=True)
    dt["coef"] = dt["variable"].map({x: y for x, y in zip(feature_names, coef)})
    dt["score"] = -np.round(b * dt["coef"] * dt["woe"])
    return pd.concat(
        [
            pd.DataFrame(
                {
                    "variable": "Base Line",
                    "bin": None,
                    "score": np.round(a - b * intercept),
                }
            ),
            dt[["variable", "bin", "score"]],
        ],
        axis=0,
        ignore_index=True,
    )


def card2sql(card, to_clipboard=True):
    """Convert scorecard DataFrame to executable SQL CASE WHEN statements.

    Automatically handles discrete tuple bins, continuous interval bins,
    missing values (NaN), and open-ended intervals.

    Parameters
    ----------
    card: DataFrame
        Scorecard DataFrame generated by `scorecard()` function.
    to_clipboard: bool, optional
        If True, copy generated SQL to system clipboard. Defaults to True.

    Returns
    -------
    sql_query: str
        Complete SQL query to calculate total credit score.
    """

    def is_tuple(value):
        return isinstance(value, tuple)

    def is_interval(value):
        return isinstance(value, pd.Interval)

    def has_nan(value):
        if not isinstance(value, tuple):
            return False
        return np.nan in value

    def filter_nan(value):
        return tuple(filter(lambda x: x == x, value))

    def is_infinite(value):
        return not np.isfinite(value)

    def format_tuple(value):
        res = []
        for x in value:
            if isinstance(x, str):
                res.append(f"'{x}'")
            elif isinstance(x, np.number):
                res.append(str(x.item()))
            else:
                res.append(str(x))
        return res

    def parse(dt):
        env = Environment(autoescape=False, trim_blocks=True, lstrip_blocks=True)
        env.filters["is_tuple"] = is_tuple
        env.filters["is_interval"] = is_interval
        env.filters["has_nan"] = has_nan
        env.filters["filter_nan"] = filter_nan
        env.filters["is_infinite"] = is_infinite
        env.filters["format_tuple"] = format_tuple
        templ = """
        case
        {% for row in dt.itertuples() %}
            {% if row.bin | is_tuple %}
                {% if row.bin | has_nan %}
                    {% if len(row.bin) == 1 %}
            when {{ row.variable }} is null then {{ row.score }}
                    {% else %}
            when {{ row.variable }} is null or {{ row.variable }} in ({{ row.bin | filter_nan | format_tuple | join(',') }}) then {{ row.score }}
                    {% endif %}
                {% else %}
            when {{ row.variable }} in ({{ row.bin | format_tuple | join(',') }}) then {{ row.score }}
                {% endif %}
            {% elif row.bin | is_interval %}
                {% if row.bin.right | is_infinite %}
            else {{ row.score }}
                {% else %}
            when {{ row.variable }} <= {{ row.bin.right }} then {{ row.score }}
                {% endif %}
            {% else %}
            else {{ row.score }}
            {% endif %}
        {% endfor %}
        end
        """  # noqa
        return env.from_string(templ).render({"dt": dt})

    variables = card.iloc[1:, 0].unique()
    result = [str(card.iloc[0, 2])]
    for variable in variables:
        result.append(parse(card.loc[card["variable"] == variable, :]))
    result = " + ".join(result)
    if to_clipboard:
        pyperclip.copy(result)
    return result
